### ISSUE TITLE
A couple usability requests

### ISSUE THREAD

**Issue by faeldray** [MineSpeed200/Torchplacer#1]
In 1.16.4, there doesn't appear to be a way to change the hotkey to something other than B.

Also, while the `/torch` command is useable, Minecraft thinks that it doesn't exist (see image below).

![image](https://user-images.githubusercontent.com/967709/113450049-be450700-93c4-11eb-9ee2-4ee9492a4ef4.png)

Also if you could tag the mod for 1.16.5 on Curseforge, that would be great. I've tested it and it works fine in 1.16.5.

**Comment by MineSpeed200** [comment]
I am aware of the issue, that Minecraft isn't aware of the command tho i don't know why. I am going to look into the keybind and thanks for testing it for 1.16.4

**Comment by MineSpeed200** [comment]
I've just released a fixed version for 1.16.x, i am going to test it for 1.15.x but ther will probably be nothing wrong with it.

**Comment by faeldray** [comment]
Awesome! I see the update on the Curseforge page but clicking the link gives me a "Not found" page. I take it it's still waiting for approval?

**Comment by faeldray** [comment]
Nevermind, I can update it through the client, Curseforge is just being weird again.
