### ISSUE TITLE
Crash when torch is trying to be placed on a server

### ISSUE THREAD

**Issue by faeldray** [MineSpeed200/Torchplacer#2]
I've set up a multiplayer server for my modpack and we've begun experiencing a server crash whenever a player has torch placing enabled and the mod attempts to place a torch. I haven't had the chance to test out if the same thing occurs on single player yet (we just discovered the bug tonight).

https://gist.github.com/faeldray/132b74aab085ce17e7d27ec14e78cc3a

**Comment by MineSpeed200** [comment]
I knew i should have tested it on a dedicated server... Thanks i am going to look into it

**Comment by MineSpeed200** [comment]
I've compiled a possible fix, you can download it [here](https://minespeed200.de/files/Torchplacer-1.16-v1.0.2.jar). I will do further test throughout the day.

**Comment by faeldray** [comment]
That seems to have fixed it. Thanks for doing that so quickly!
